### ISSUE TITLE
Use CSS for QRCode SVG color to reduce output size

### ISSUE THREAD

**Issue by tanguilp** [iodevs/qr_code#30]
As of today squares are generated with the color as an attribute:

```svg
<rect fill="#4169e1" height="10" width="10" x="0" y="480"/>
```

A CSS stylesheet could be used to reduce the size of the output. Something like:

```svg
<svg>
<style type="text/css">rect {fill: #4169e1}</style>
<rect fill="#ffffff" height="100%" width="100%"/>
<rect height="10" width="10" x="0" y="480"/>
<rect height="10" width="10" x="0" y="470"/>
<rect height="10" width="10" x="0" y="460"/>
<rect height="10" width="10" x="0" y="450"/>
```

As a side note, `x` and `y` default to `0`, so no need to set them to that value.

**Comment by tanguilp** [comment]
You're absolutely right, `style` attribute has precedence over other sources of CSS, `fill` hasn't.

**Comment by ondrej-tucek** [comment]
I did some comparison with qrcode files with and without `x="0"`, `y="0"` for different levels. See table below. 

On based of these results I think it's no need to remove these zeros because of reducing size hasn't so impact huge. As you can see the difference is around 1kB and this is for maximal length of coded string. In real case it will be less.

| Level                   |   :low  | :medium | :quartile |  :high  |
|-------------------------|:-------:|:-------:|:---------:|:-------:|
| max length of coded string    |  2953 | 2331 | 1663 | 1273   |
| qrcode size [B]         |         |         |           |         |
| -- with x="0" and y="0"    | 828_046 | 820_828 |  822_726  | 817_716  |
| -- without x="0" and y="0" |  826_882 | 819_700 | 821_586 | 816_456 |
| difference [B]          | 1164 | 1128 | 1140 | 1260  |
|                         |         |         |           |         |
